title: "Nathaniel Ingle's ePortfolio"
description: "An online portfolio presenting artifacts from my computer science program."
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme 
