# Generated by Django 5.2.4 on 2025-08-03 20:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weighin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weighin',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 8, 3, 20, 8, 18, 67206, tzinfo=datetime.timezone.utc)),
        ),
    ]
